services:
  - type: web
    name: juanstore
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: j4unSt0r3_s3cr3t_k3y_2026_x9mP
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: "Juan$2026!Store"
      - key: ALLOWED_ORIGIN
        sync: false
